config/routes.rb
BeerRatings::Application.routes.draw do
  resources :ratings
  root to: 'ratings#index'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	validates :score, presence: true, :inclusion => 1..10
	validates :when_rated, presence: true

	def self.search(query)
		words = query.to_s.strip.split
		words.inject(scoped) do |combined_scope, word|
			combined_scope.where("name ILIKE ?", "%#{word}%")
		end
	end

	def self.sort(sortby)
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # GET /ratings
  # GET /ratings.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ratings_by_name }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.json
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(params[:rating])

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render json: @rating, status: :created, location: @rating }
      else
        format.html { render action: "new" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.json
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerRatings</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
        <a class="brand" href="http://beerratings.herokuapp.com">Jason's Beer Ratings</a>
				<!--<ul class="nav">
					<li><%= link_to "Full List", ratings_path %></li>
				</ul>-->
				<form class="navbar-search">
      		<input type="text" class="search-query span2" placeholder="Find Some Beers" name="search">
    			<div class="icon-search"></div>
     		</form>
			</div>
		</div>
	</div>

	<div class="container content-main">
		<%= yield %>
	</div>

</body>

</html>

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :when_rated %><br />
    <%= f.date_select :when_rated %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<div class="tab-pane active" id="tab1">
  <% @ratings_by_name = Rating.search(params[:search]).paginate(:order => 'name ASC', :page => params[:page], :per_page =>10) %>
  <% @ratings_by_name.each do |rating| %>
  <div class="rating">
    <div class="row">
      <div class="span7">
        <strong><%= rating.name %></strong>
        <div class="meta">
            | <%= link_to 'View', rating %> | 
          <span class="admin">
            <%= link_to 'Edit', edit_rating_path(rating) %> | 
          </span>
          Rated on <%= rating.when_rated %>
        </div>
      </div>   
      <div class="span2">
        <%= rating.score %>
      </div>
    </div>
  </div>
<!-- <%= link_to 'Edit', edit_rating_path(rating) %>
<%= link_to 'Destroy', rating, confirm: 'Are you sure?', method: :delete %> --> 
  <% end %>
  <%= will_paginate @ratings_by_name %>
</div>

 

<!-- <%= link_to 'New Rating', new_rating_path %> -->

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rating.name %>
</p>

<p>
  <b>Score:</b>
  <%= @rating.score %>
</p>

<p>
  <b>When rated:</b>
  <%= @rating.when_rated %>
</p>

<p>
  <b>Comment:</b>
  <%= @rating.comment %>
</p>


<!-- <%= link_to 'Edit', edit_rating_path(@rating) %> | -->
<%= link_to 'Back', ratings_path %>